### PR TITLE
Improve formatting and grammar

### PR DESCRIPTION
**Pull request by karlhorky**

### CODE REVIEW

**Comment by rafamel** [comment]
Hey Karl, great to see you chip in too :)

I was thinking about a way of signalling the difference in the shortcuts for windows/linux vs. macos.

What do you think about <kbd>ctrl(⌘)</kbd> ?

Also, the <kbd>[n]</kbd> seems a bit out of place. Maybe <kbd>ctrl(⌘)</kbd> + <kbd>alt</kbd> + *n* ?

**Comment by karlhorky** [comment]
Sure, doing this now.

**Comment by karlhorky** [comment]
Hm, still not 100% satisfied with it, but here is what I have right now:

<kbd>ctrl / cmd</kbd>

Looks like this in the full readme:

screen shot 2017-06-06 at 16 20 38

**Comment by karlhorky** [comment]
Probably too verbose, right?

The reason I went away from <kbd>ctrl(⌘)</kbd> was that it looked a bit cryptic... if you still like it I can put it back though.

**Comment by karlhorky** [comment]
What about just using <kbd>cmd</kbd> or <kbd>ctrl</kbd> and then including a sentence for "If you're on Windows or Linux, use <kbd>ctrl</kbd> instead of <kbd>cmd</kbd>" or vice versa.

Also not ideal... but it would make the instruction list more compact.

**Comment by rafamel** [comment]
I've merged, made some changes, and published. I finally settled with the ctrl(⌘) form. It is true it might be not 100% obvious but the other solutions where kind of clutter-ish/too verbose, as you pointed out - and I do feel anyone using Atom or the extension, for that matter, will for sure get it. Otherwise, there's always `Packages > Layout Control` to clarify! 

On a different note, I'm seeing that the [atom description](https://atom.io/packages/layout-control) doesn't render `<kbd>`. Bummer!

**Comment by karlhorky** [comment]
Sounds good, cheers!

**Comment by aversini** [comment]
Hi guys, I'm so glad I found this package! Life saver after the 1.17 Atom update that broke pretty much all layout managers. As for this PR, what about the following:

Command | Mac OS | Linux/Windows
------- | ------ | -------------
Create __n__ *columns* layout | <kbd>cmd</kbd>+<kbd>alt</kbd>+<kbd>n</kbd> | <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>n</kbd>
Create __n__ *rows* layout | <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>alt</kbd>+<kbd>n</kbd> | <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>alt</kbd>+<kbd>n</kbd>

*NOTE*: layouts are limited to a maximum of 4 columns and 3 rows.

**Comment by rafamel** [comment]
Sounds good to me! Do you wanna do a PR?

**Comment by aversini** [comment]
Absolutely @rafamel , there you go: https://github.com/rafamel/atom-layout-control/pull/2

**Pull request merged**
