### PR TITLE
doc(README): command clarification per OS

### PR DESCRIPTION
**Pull request by aversini**
Slight improvement of the commands description, with a clearer explanation between different OS.

### CODE REVIEW

**Comment by rafamel** [comment]
Merged and published, @aversini!

**Comment by rafamel** [comment]
Hey, @aversini, just wanted to let you know I've had to roll back the changes as the table wasn't properly rendered at Atom Packages :(

**Comment by aversini** [comment]
Oh no.. Sorry about that @rafamel , do you have a screenshot by any chance? I'm wondering what's breaking... I've seen other packages with the same kind of markdown tables before :/

**Comment by rafamel** [comment]
Damn! No, I didn't make a screenshot. Do you happen to have the repo of any of those packages around?

**Comment by aversini** [comment]
yes [Simple Panes](https://atom.io/packages/simple-panes) does the exact same thing.

**Comment by rafamel** [comment]
Retried and seems to be working now. I probably messed up with the formatting the first time around. Thanks!

**Pull request merged**
